export const largeFundAnaylsisLabels = [
  'total_revenue',
  'cost_of_revenue',
  'gross_profit',
  'r_and_d',
  'selling_gen_and_admin',
  'operating_expense',
  'operating_income',
  'other_income_expense_net',
  'ebit',
  'intrest_income',
  'pretax_income',
  'income_tax',
  'minority_intrest',
  'net_income',
  'net_income_basic',
  'shares_outstanding',
  'float',
  'total_cash',
  'current_debt',
  'ebitda',
  'revenue_per_employee',
  'enterprise_value',
  'depreciation',
  'changes_in_receviables',
  'changes_in_inventories',
  'cash_change',
  'cash_flow',
  'capital_expenditures',
  'investments',
  'total_investing_cash_flows',
  'dividends_paid',
  'net_borrowings',
  'other_cash_flows',
  'cash_flow_financing',
  'current_cash',
  'short_term_investments',
  'receivables',
  'inventory',
  'other_current_assets',
  'current_assets',
  'long_term_investments',
  'property_plant_equipment',
  'goodwill',
  'intangible_assets',
  'other_assets',
  'total_assets',
  'accounts_payable',
  'current_long_term_debt',
  'other_current_liabilites',
  'total_current_liabilites',
  'long_term_debt',
  'other_liabilites',
  'minority_interest',
  'total_liabilites',
  'common_stock',
  'retained_earnings',
  'treasury_stock',
  'capital_surplus',
  'shareholder_equity',
  'net_tangible_assets',
  'intangibles_book_ratio',
  'working_capital',
];

export const mediumFundAnaylsisLabels = [
  'yr_change',
  'employees',
  'revenue_per_share',
  'institutional_ownership',
  'short_interest_percent',
  'book_value'
];

export const smallFundAnaylsisLabels = [
  'eps_ttm',
  'dividend_yield',
  'dividend_rate_ttm',
  'pe_ratio',
  'beta',
  'debt_to_equity',
  'profit_margin',
  'enterprise_value_to_rev',
  'price_to_sales',
  'price_to_book',
  'foward_pe_ratio',
  'peg_ratio',
  'pe_high',
  'pe_low',
  'quick_ratio',
  'current_ratio',
  'total_debt_equity_ratio',
  'long_term_debt_equity',
  'short_term_debt_equity',
  'inventory_to_sales_ratio',
  'long_term_debt_percent_invest_cap',
  'short_term_debt_percent_invest_cap',
  'long_term_debt_to_total_debt',
  'short_term_debt_to_total_debt',
  'total_liabilites_to_total_assets',
];

export const chartAnaylsisLabels = [
  'two_crows',
  'three_black_crows',
  'three_inside_up_down',
  'three_outside_up_down',
  'three_line_strike',
  'three_stars_south',
  'three_adv_soliders',
  'abandoned_baby',
  'advance_block',
  'belt_hold',
  'breakaway',
  'marubozu_closing',
  'concealing_baby_swallow',
  'counterattack',
  'dark_cloud_cover',
  'doji',
  'doji_star',
  'doji_dragonfly',
  'engulfing_pattern',
  'gravestone_doji',
  'hammer',
  'hanging_man',
  'harami_pattern',
  'harami_cross_pattern',
  'high_wave_candle',
  'hikkake_pattern',
  'hikkake_mod_pattern',
  'homing_pigeon',
  'identical_three_crows',
  'in_neck_pattern',
  'inverted_hammer',
  'kicking',
  'ladder_bottom',
  'doji_long_leg',
  'long_line_candle',
  'marubozu',
  'matching_low',
  'mat_hold',
  'doji_morning_star',
  'morning_star',
  'on_neck_pattern',
  'piercing_pattern',
  'rickshaw_man',
  'rise_fall_three_methods',
  'seperating_lines',
  'shooting_star',
  'short_line_candle',
  'spinning_top',
  'stalled_pattern',
  'stick_sandwhich',
  'doji_tasuki',
  'tasuki_gap',
  'thrusting_pattern',
  'tristar_pattern',
  'three_unique_river',
  'three_upside_gap_river'
];

export const smallTechAnaylsisLabels = [
  'atr_3_period',
  'atr_10_period',
  'atr_15_period',
  'atr_20_period',
  'boll_bands_upper_3_period',
  'boll_bands_middle_3_period',
  'boll_bands_lower_3_period',
  'boll_bands_upper_10_period',
  'boll_bands_middle_10_period',
  'boll_bands_lower_10_period',
  'boll_bands_upper_15_period',
  'boll_bands_middle_15_period',
  'boll_bands_lower_15_period',
  'boll_bands_upper_20_period',
  'boll_bands_middle_20_period',
  'boll_bands_lower_20_period',
  'sma_3_period',
  'sma_10_period',
  'sma_15_period',
  'sma_20_period',
  'ema_3_period',
  'ema_10_period',
  'ema_15_period',
  'ema_20_period',
  'balance_of_power',
  'chande_momentum_oscillator_15_period',
  'chande_momentum_oscillator_20_period',
  'pearsons_coeff_close_vol_5_period',
  'pearsons_coeff_close_vol_15_period',
  'pearsons_coeff_close_vol_30_period',
  'pearsons_coeff_close_avg_vol_5_period',
  'pearsons_coeff_close_avg_vol_15_period',
  'pearsons_coeff_close_avg_vol_30_period',
  'pearsons_coeff_close_spy_5_period',
  'pearsons_coeff_close_spy_15_period',
  'pearsons_coeff_close_spy_30_period',
  'double_ema_3_period',
  'double_ema_10_period',
  'double_ema_15_period',
  'double_ema_20_period',
  'kaufman_adaptive_ma_5_period',
  'kaufman_adaptive_ma_15_period',
  'kaufman_adaptive_ma_30_period',
  'linear_reg_3_period',
  'linear_reg_10_period',
  'linear_reg_15_period',
  'linear_reg_20_period',
  'linear_reg_angle_3_period',
  'linear_reg_angle_10_period',
  'linear_reg_angle_15_period',
  'linear_reg_angle_20_period',
  'linear_reg_intercept_3_period',
  'linear_reg_intercept_10_period',
  'linear_reg_intercept_15_period',
  'linear_reg_intercept_20_period',
  'linear_reg_slope_3_period',
  'linear_reg_slope_10_period',
  'linear_reg_slope_15_period',
  'linear_reg_slope_20_period',
  'macd_fast_12_slow_26_sig_9',
  'macd_signal_fast_12_slow_26_sig_9',
  'macd_hist_fast_12_slow_26_sig_9',
  'macd_fast_6_slow_13_sig_5',
  'macd_signal_fast_6_slow_13_sig_5',
  'macd_hist_fast_6_slow_13_sig_5',
  'macd_fast_18_slow_39_sig_14',
  'macd_signal_fast_18_slow_39_sig_14',
  'macd_hist_fast_18_slow_39_sig_14',
  'mesa_adaptive_ma_mama',
  'mesa_adaptive_ma_fama',
  'momentum_3_period',
  'momentum_10_period',
  'momentum_15_period',
  'momentum_20_period',
  'percent_price_osc_fast_6_slow_13',
  'percent_price_osc_fast_12_slow_26',
  'percent_price_osc_fast_18_slow_38',
  'parabolic_sar',
  'parabolic_sar_ext',
  'std_deviation_3_period',
  'std_deviation_10_period',
  'std_deviation_15_period',
  'std_deviation_20_period',
  'std_deviation_dbl_3_period',
  'std_deviation_dbl_10_period',
  'std_deviation_dbl_15_period',
  'std_deviation_dbl_20_period',
  'triple_ema_3_period',
  'triple_ema_10_period',
  'triple_ema_15_period',
  'true_range',
  'triangluar_ma_15_period',
  'triangluar_ma_30_period',
  'weighted_ma_3_period',
  'weighted_ma_10_period',
  'weighted_ma_15_period',
  'weighted_ma_20_period'
];

export const mediumTechAnaylsisLabels = [
  'average_directional_movement_3_period',
  'average_directional_movement_10_period',
  'average_directional_movement_15_period',
  'average_directional_movement_20_period',
  'commodity_channel_index_3_period',
  'commodity_channel_index_10_period',
  'commodity_channel_index_15_period',
  'commodity_channel_index_20_period',
  'chande_momentum_oscillator_3_period',
  'chande_momentum_oscillator_10_period',
  'directional_movement_index_3_period',
  'directional_movement_index_10_period',
  'directional_movement_index_15_period',
  'directional_movement_index_20_period',
  'money_flow_index_3_period',
  'money_flow_index_10_period',
  'money_flow_index_15_period',
  'money_flow_index_20_period',
  'normalized_atr_3_period',
  'normalized_atr_10_period',
  'normalized_atr_15_period',
  'normalized_atr_20_period',
  'rsi_3_period',
  'rsi_10_period',
  'rsi_15_period',
  'rsi_20_period',
  'stochastic_sk_fast_5_slow_k_3_slow_d_3',
  'stochastic_sd_fast_5_slow_k_3_slow_d_3',
  'stochastic_sk_fast_20_slow_k_7_slow_d_7',
  'stochastic_sd_fast_20_slow_k_7_slow_d_7',
  'stochastic_sk_fast_20_slow_k_14_slow_d_14',
  'stochastic_sd_fast_20_slow_k_14_slow_d_14',
  'ultimate_osc_3_6_12_period',
  'ultimate_osc_7_14_28_period',
  'ultimate_osc_10_20_40_period',
  'williams_percent_r_3_period',
  'williams_percent_r_10_period',
  'williams_percent_r_15_period',
  'williams_percent_r_20_period',
];

export const largeTechAnaylsisLabels = [
  'chaikin_osc_fast_3_slow_10',
  'chaikin_osc_fast_6_slow_18',
  'chaikin_osc_fast_10_slow_20',
  'chaikin_a_d_line',
  'obv'
];

export const eodPriceActionLabels = [
  'percent_change',
  'vol_diff_from_avg',
  'price_diff_open_to_low'
];

export const wkPriceActionLabels = [
  'percent_change',
  'vol_diff_from_avg',
  'price_diff_open_to_low'
];

export const tableInfoLabels = [
  'Ticker',
  'Last News Article',
  'Percent Change',
  'Earnings Date',
  'ADR',
  'Date of IPO'
];

export const secTableLabels = [
  'Ticker',
  'Date of IPO',
  'ADR'
];

export const secLabels = [
  'CT Orders',
  '# of Mergers',
  'Late Filings',
  '# of Employee Diluations',
  '# of Company Diluations',
  'Total # of Diluations'
];